# Configuração de proteção de branch para o repositório R5 Flowlight
# Esta configuração será aplicada via GitHub API

# Configuração para a branch main
required_status_checks:
  strict: true
  contexts:
    - "check-formatting"
    - "test"
    - "build"
enforce_admins: false
required_pull_request_reviews:
  required_approving_review_count: 1
  require_code_owner_reviews: true
  dismiss_stale_reviews: true
  require_last_push_approval: true
restrictions: null
required_linear_history: true
allow_force_pushes: false
allow_deletions: false
required_conversation_resolution: true
lock_branch: false
allow_fork_syncing: true
